### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by nevrome** [nevrome/covid19germany#6]
- [x] Plotidee mit den zusammengetragenen Daten entwickeln und implementieren. Möglichst dicht, aber auch leicht verständlich und optisch ansprechend. Davon hängt viel ab! Wahrscheinlich macht es Sinn, eine extra Kartenplot-Funktion zu entwickeln. Oder wir führen mehrere Plots in einem Plot-Panel zusammen, das von einer Funktion generiert wird.
- [x] Join der Einwohnerdaten und der Krankheitsdaten erfordert etwas mehr Finesse, da eine ID-Spalte als Fremdschlüssel erforderlich ist. Die muss nach (oder am Ende derselben?) der group-Funktion wieder an die Tabelle ran 
- [ ] Funktions- und Datennamen (vllt. auch Variablen-/Spaltennamen) überdenken
- [x] Paketdoku überarbeiten (Funktions- und Datensatzdoku ist grade noch sehr roh). Insbesondere fehlen Referenzen für die Datensätze (siehe auch https://www.govdata.de/dl-de/by-2-0)
- [x] CI für das Backend-Paket einrichten, um technische Fehler schneller zu bemerken. Vielleicht ein paar einfache Unittests schreiben.

Darstellung in der App:
- [ ] Angefittetes Modell für BLs/LKs, mit 2-3 Wochen Prognose zeigen ("min. 20 kumulative Fälle-Regel" anwenden). Wäre denke ich für die Präsentation ein großer Mehrwert gegenüber bestehenden Dashboard-Seiten. Man müsste dafür aber vermutl. einzelne räumliche Einheiten auswählen können (am besten ntl. per Karte, aber die Zeit ist dafür doch recht knapp).
- [ ] Darstellung nach LK auf einzelnes BL beschränken, ist sonst zu viel.
- [ ] Prävalenz: Fälle pro 100k EW für Darstellung nach LK und BL (s. Beispiele Repo README). Das mach die räumlichen Einheiten vergleichbar.
- [ ] Wachstumsraten u/o Verdopplungszeiten (Code hier irgendwo im Channel)? Running mean 7 Tage oder so. Zur Motivation, damit man sieht dass/ob die Maßnahmen wirken. Ist einfacher zu verstehen als eine Log-Darstellung mit evtl. "abknickender Gerade".

Cloropleth Plots mit allen Landkreisen in Deutschland:
- [ ] Aktuelle Fallzahlen
- [ ] Aktuelle Inzidenzraten pro 100k
- [ ] Aktuelle Todesfälle
- [ ] Aktuelle Todesraten pro 100k
- [ ] Aktuelle Verdopplungszeiten
- [ ] Das gleich könnte man als Cloropleth plot pro Bundesland machen.
- [ ] Außerdem sollte es die Möglichkeit zur Extrapolation geben, also etwa all diese Plots 3 Wochen in die Zukunft projiziert.
- [ ] Wenn auch noch Krankenhaus-Betten zur Verfügung stehen könnte man noch Fallzahlen pro Krankenhausbett plotten, ebenfalls mit Extrapolation.

**Comment by stschiff** [comment]
Und für die Submission:
[] Rausfinden was an Text-Bausteinen nötig ist (Zusammenfassung, Beschreibung, oder reicht das auf Devpost?)
[] Video? Machen? Wie?

**Comment by stschiff** [comment]
Looks to me pretty much done, this issue. Close?
